#if !defined(AFX_TV_H__62560B25_961B_47CC_8540_1E691168C9AA__INCLUDED_)
#define AFX_TV_H__62560B25_961B_47CC_8540_1E691168C9AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTV wrapper class

class CTV : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTV)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcd6c7868, 0x5864, 0x11d0, { 0xab, 0xf0, 0x0, 0x20, 0xaf, 0x6b, 0xb, 0x7a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TV_H__62560B25_961B_47CC_8540_1E691168C9AA__INCLUDED_)
